module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#e5e2df",
        "on-tertiary": "#ffffff",
        "primary-container": "#a26551",
        "surface-container": "#ffe9e2",
        "on-secondary-fixed": "#1c1b1a",
        primary: "#854d3b",
        "surface-bright": "#fff8f6",
        "on-surface-variant": "#52433f",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#c9c6c3",
        "inverse-surface": "#3c2d27",
        secondary: "#605e5c",
        "surface-dim": "#eed5cc",
        "on-secondary-fixed-variant": "#484745",
        surface: "#fff8f6",
        "on-tertiary-fixed": "#241a0e",
        "on-surface": "#261913",
        "surface-container-low": "#fff1ec",
        "on-primary-fixed": "#360f03",
        "surface-container-high": "#fce3da",
        outline: "#85736e",
        "on-secondary-container": "#666462",
        "on-tertiary-fixed-variant": "#524436",
        "tertiary-container": "#827261",
        "tertiary-fixed": "#f4dfcb",
        "inverse-primary": "#feb59d",
        "surface-tint": "#88503d",
        "on-primary-container": "#fffbff",
        "surface-container-highest": "#f6ddd4",
        "on-tertiary-container": "#fffbff",
        "on-background": "#261913",
        "outline-variant": "#d7c2bc",
        "primary-fixed": "#ffdbd0",
        background: "#fff8f6",
        "inverse-on-surface": "#ffede7",
        "on-primary-fixed-variant": "#6c3927",
        "surface-variant": "#f6ddd4",
        tertiary: "#68594a",
        "secondary-fixed": "#e5e2df",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#feb59d",
        "tertiary-fixed-dim": "#d7c3b0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "24px",
        "section-gap": "120px",
        gutter: "32px",
        "container-max": "1280px",
        unit: "8px",
      },
      fontFamily: {
        "label-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-lg-mobile": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "headline-md": ["Montserrat"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
